# Site settings
title: Kevin Armstrong
email: kevin@the-armstrongs.org
author: Kevin Armstrong
description: "Capital Efficiency | Security Strategy | Identity Architecture"
linkedin_url: "https://www.linkedin.com/in/kevinsarmstrong"

# Collections Configuration
collections:
  briefs:
    output: true
    permalink: /briefs/:title/

# Default layout for posts in briefs collection.
defaults:
  - scope: { type: "briefs" }
    values: { layout: "post" }