# Site settings
title: Kevin Armstrong | Strategic IT Executive & Architect
author: Kevin Armstrong
email: kevin@the-armstrongs.org
description: >-
  Strategic Systems Architect specialized in risk mitigation, capital efficiency, and identity strategy (CIAM/IAM).
url: "https://kasurot.github.io"
linkedin_url: "https://linkedin.com/in/kevinsarmstrong"